services:
    client:
        build: ./client
        image: cyannav-client
        container_name: client
        ports:
            - "80:80"
            - "443:443"
        restart: always
        depends_on:
            - server
        networks:
            - mern-networks
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt

    server:
        build: ./server
        image: cyannav-api
        container_name: api-server
        ports:
            - "8000:8000"
        restart: always
        depends_on:
            - database
        networks:
            - mern-networks

    database:
        image: mongo
        container_name: mongo-db
        ports:
            - "27017:27017"
        restart: always
        networks:
            - mern-networks

networks:
    mern-networks:
        driver: bridge
