name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    setup:
        runs-on: self-hosted

        steps:
            - name: Checkout main repo
              uses: actions/checkout@v4
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: Install node dependencies
              run: |
                  npm i --force
                  cd client
                  npm i --force
                  cd ../server
                  npm i --force
                  npm --version
                  node --version

    lint:
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Lint
              run: |
                  echo "Linting to be implemented"

    frontend-test:
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Frontend Cypress test
              run: |
                  npm --version
                  node --version
                  npx cypress run

    backend-test:
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Backend API test
              run: |
                  echo "To be implemented"

    build-frontend:
        needs: frontend-test
        runs-on: self-hosted

        steps:
            - name: Build frontend
              run: |
                  cd client
                  npm run build

    deploy-backend:
        needs: backend-test
        runs-on: self-hosted

        steps:
            - name: Deploy backend server
              run: |
                  cd server
                  pm2 stop 0
                  pm2 start 0

    deploy-frontend:
        needs: build-frontend
        runs-on: self-hosted

        steps:
            - name: Deploy frontend server
              run: |
                  sudo service nginx restart
