name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    setup:
        runs-on: self-hosted
        environment: cyannav

        steps:
            - name: Checkout main repo
              uses: actions/checkout@v4
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: Install node dependencies
              run: |
                  npm i --force
                  cd client
                  npm i --force
                  cd ../server
                  npm i --force
            - name: Create environment for backend
              run: |
                  cd server
                  rm .env
                  touch .env
                  echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
                  echo SERVER_HOSTNAME=${{ vars.SERVER_HOSTNAME }} >>.env
                  echo SERVER_PORT=${{ vars.SERVER_PORT }} >> .env
                  echo JWT_EXPIRATION_TIME=${{ vars.JWT_EXPIRATION_TIME }} >> .env

    lint:
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Lint
              run: |
                  echo "Linting to be implemented"

    frontend-test:
        needs: build-frontend
        runs-on: self-hosted

        steps:
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: Frontend Cypress test
              run: |
                  npx cypress run

    backend-test:
        needs: deploy-frontend
        runs-on: self-hosted

        steps:
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: Backend API test
              run: |
                  cd server
                  npm test

    build-frontend:
        needs: setup
        runs-on: self-hosted

        steps:
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                  node-version: "21.x"
            - name: Build frontend
              run: |
                  cd client
                  npm run build

    deploy-backend:
        needs: backend-test
        runs-on: self-hosted

        steps:
            - name: Deploy backend server
              run: |
                  cd server
                  pm2 start 0

    deploy-frontend:
        needs: build-frontend
        runs-on: self-hosted

        steps:
            - name: Deploy frontend server
              run: |
                  sudo service nginx restart
