name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - run: |
          npm i --force
          cd client
          npm i --force
          npm run build
          sudo service nginx restart
          cd ../server
          npm i --force
          pm2 stop 0
          pm2 start 0
          cd ..
          npx cypress run
