name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js latest
      uses: actions/setup-node@v1
      with:
        node-version: latest
    - run:
        cd client
        npm i
        npm run build
        cd ../server
        npm i
